name: Lint
on:
  push:
    branches: [master, release]
  pull_request:

jobs:
  lint-solidity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.0"
      - name: Install dependencies
        run: npm ci

      - name: Lint Solidity
        run: npm run lint:sol

  lint-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.0"
      - name: Install dependencies
        run: npm ci

      - name: Lint Typescript
        run: npm run lint:ts
