name: CI testing

on:
  push:
    branches: [master, release]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ARBITRUM_URI: ${{ secrets.ARBITRUM_URI }}
      GOERLI_URI: ${{ secrets.GOERLI_URI }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.0"

      - name: Install dependencies
        run: npm ci

      - name: Generate typechain typings
        run: npm run typechain

      - name: Run Tests
        run: npm run test
